import "./components/fc-footer.js"
import "./pages/fc-repaircard.js"
import "./components/fc-header.js"
import "./components/edit-string.js"
import "./components/main-form.js"
import "./vaadin-router.js"
import "./pages/dummy-page.js"
